cloud.microservice.name=${MICROSERVICE_NAME:consul-login-test-service-quarkus}
cloud.microservice.namespace=${CLOUD_NAMESPACE:unknown}

quarkus.http.port=8080
quarkus.log.level=${LOG_LEVEL:INFO}
quarkus.log.console.level=${LOG_LEVEL:INFO}
quarkus.log.category."com.netcracker.cloud.consul".level=DEBUG

quarkus.consul-source-config.enabled=true
quarkus.consul-source-config.agent.url=${CONSUL_URL:http://consul-consul-server.consul:8500/}
quarkus.consul-source-config.properties-root=config/${cloud.microservice.namespace}/application,config/${cloud.microservice.namespace}/${cloud.microservice.name}

consul.auth.mode=kubernetes
consul.auth.method=unset
consul.auth.audience=netcracker
consul.auth.fallback-recheck-interval=5m
