cloud.microservice.name=${MICROSERVICE_NAME:consul-login-test-service-quarkus}
cloud.microservice.namespace=${CLOUD_NAMESPACE:unknown}

quarkus.http.port=8080
quarkus.log.level=${LOG_LEVEL:INFO}
quarkus.log.console.level=${LOG_LEVEL:INFO}
quarkus.log.category."com.netcracker.cloud.consul".level=DEBUG

quarkus.consul-source-config.enabled=true
quarkus.consul-source-config.agent.url=${CONSUL_URL:http://consul-consul-server.consul:8500/}
quarkus.consul-source-config.properties-root=config/${cloud.microservice.namespace}/application,config/${cloud.microservice.namespace}/${cloud.microservice.name}

quarkus.consul-source-config.login.mode=${CONSUL_LOGIN_MODE:kubernetes}
quarkus.consul-source-config.login.auth-method=${CONSUL_LOGIN_AUTH_METHOD:unset}
quarkus.consul-source-config.login.audience=${CONSUL_LOGIN_AUDIENCE:netcracker}
quarkus.consul-source-config.login.fallback-recheck-interval=${CONSUL_LOGIN_RECHECK:5m}
