kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: consul-poc
kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    apiServer:
      extraArgs:
        service-account-lookup: "true"
nodes:
  - role: control-plane
    image: kindest/node:v1.34.0
    extraPortMappings:
      - containerPort: 30850
        hostPort: 8500
        protocol: TCP
