kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: consul-poc
nodes:
  - role: control-plane
    image: kindest/node:v1.34.0
    extraPortMappings:
      - containerPort: 30850
        hostPort: 8500
        protocol: TCP
