{{- if eq .Values.SERVICE_MESH_TYPE "Istio" }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: mesh-test-service-go-public-routes
  namespace: {{ .Values.NAMESPACE }}
spec:
  parentRefs:
    - name: public-gateway
    - name: private-gateway
    - name: internal-gateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /api/v1/mesh-test-service-go/1234
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /api/v1/1234
      backendRefs:
        - name: {{ .Values.DEPLOYMENT_RESOURCE_NAME }}
          port: 8080
    - matches:
        - path:
            type: PathPrefix
            value: /api/v1/mesh-test-service-go
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /api/v1
      backendRefs:
        - name: {{ .Values.DEPLOYMENT_RESOURCE_NAME }}
          port: 8080
{{- end }}
