name: Setup Kind cluster and deploy Cloud Core
description: >
  Spins up a Kind cluster, installs required tooling, checks out the
  qubership-core-bootstrap repo, and deploys Cloud Core with Core or Istio serivce mesh.

inputs:
  core-bootstrap-branch:
    description: Branch of the qubership-core-bootstrap repo to check out
    required: false
    default: main
  test-branch:
    description: Branch of the repos for test (common for all, 'main' if absent)
    required: false
    default: 'main'
  facade-operator-tag:
    description: Docker image tag for Facade Operator
    required: false
    default: latest
  ingress-gateway-tag:
    description: Docker image tag for Ingress Gateway
    required: false
    default: latest
  control-plane-tag:
    description: Docker image tag for Control Plane
    required: false
    default: latest
  paas-mediation-tag:
    description: Docker image tag for PaaS Mediation
    required: false
    default: latest
  dbaas-agent-tag:
    description: Docker image tag for DBaaS Agent
    required: false
    default: latest
  core-operator-tag:
    description: Docker image tag for Core Operator
    required: false
    default: latest
  config-server-tag:
    description: Docker image tag for Config Server
    required: false
    default: latest
  site-management-tag:
    description: Docker image tag for Site Management
    required: false
    default: latest
  install-maas:
    description: Whether to install MaaS (also sets CORE_CONFIG_MAAS_ENABLED)
    required: false
    default: 'false'
  install-istio:
    description: Whether to install Istio
    required: false
    default: 'true'
  service-mesh-type:
    description: Service mesh type 'Core' or 'Istio'
    required: false
    default: 'Core'
  istio-repo-branch:
    description: Branch of the Istio repo
    required: false
    default: 'main'
  core-mesh-config-repo-branch:
    description: Branch of the Core Mesh Config repo
    required: false
    default: 'main'

runs:
  using: composite
  steps:
    - name: Add cluster.local to hosts
      shell: bash
      run: |
        echo "127.0.0.1 cluster.local" | sudo tee -a /etc/hosts

    - name: Set up Kind
      uses: helm/kind-action@v1.12.0
      with:
        cluster_name: kind

    # Install Helm 4 - required by core-mesh-config
    - name: Install Helm 4
      uses: azure/setup-helm@v4
      with:
         version: v4.0.1  

    - name: Set up kubectl
      uses: azure/setup-kubectl@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: temurin

    - name: Checkout cloud core bootstrap repo
      uses: actions/checkout@v4
      with:
        repository: Netcracker/qubership-core-bootstrap
        ref: ${{ inputs.core-bootstrap-branch }}
        path: core-bootstrap-repo

    - name: Deploy cloud core
      shell: bash
      run: |
        MAKE_ARGS="INSTALL_MAAS=${{ inputs.install-maas }} CORE_CONFIG_MAAS_ENABLED=${{ inputs.install-maas }} INSTALL_ISTIO=${{ inputs.install-istio }} TEST_BRANCH=${{ inputs.test-branch }}"
        FACADE_OPERATOR_TAG="${{ inputs.facade-operator-tag }}"
        INGRESS_GATEWAY_TAG="${{ inputs.ingress-gateway-tag }}"
        CONTROL_PLANE_TAG="${{ inputs.control-plane-tag }}"
        PAAS_MEDIATION_TAG="${{ inputs.paas-mediation-tag }}"
        DBAAS_AGENT_TAG="${{ inputs.dbaas-agent-tag }}"
        CORE_OPERATOR_TAG="${{ inputs.core-operator-tag }}"
        CONFIG_SERVER_TAG="${{ inputs.config-server-tag }}"
        SITE_MANAGEMENT_TAG="${{ inputs.site-management-tag }}"
        if [ "$FACADE_OPERATOR_TAG" != "latest" ] && [ -n "$FACADE_OPERATOR_TAG" ]; then
          MAKE_ARGS="$MAKE_ARGS FACADE_OPERATOR_TAG=$FACADE_OPERATOR_TAG"
        fi
        if [ "$INGRESS_GATEWAY_TAG" != "latest" ] && [ -n "$INGRESS_GATEWAY_TAG" ]; then
          MAKE_ARGS="$MAKE_ARGS INGRESS_GATEWAY_TAG=$INGRESS_GATEWAY_TAG"
        fi
        if [ "$CONTROL_PLANE_TAG" != "latest" ] && [ -n "$CONTROL_PLANE_TAG" ]; then
          MAKE_ARGS="$MAKE_ARGS CONTROL_PLANE_TAG=$CONTROL_PLANE_TAG"
        fi
        if [ "$PAAS_MEDIATION_TAG" != "latest" ] && [ -n "$PAAS_MEDIATION_TAG" ]; then
          MAKE_ARGS="$MAKE_ARGS PAAS_MEDIATION_TAG=$PAAS_MEDIATION_TAG"
        fi
        if [ "$DBAAS_AGENT_TAG" != "latest" ] && [ -n "$DBAAS_AGENT_TAG" ]; then
          MAKE_ARGS="$MAKE_ARGS DBAAS_AGENT_TAG=$DBAAS_AGENT_TAG"
        fi
        if [ "$CORE_OPERATOR_TAG" != "latest" ] && [ -n "$CORE_OPERATOR_TAG" ]; then
          MAKE_ARGS="$MAKE_ARGS CORE_OPERATOR_TAG=$CORE_OPERATOR_TAG"
        fi
        if [ "$CONFIG_SERVER_TAG" != "latest" ] && [ -n "$CONFIG_SERVER_TAG" ]; then
          MAKE_ARGS="$MAKE_ARGS CONFIG_SERVER_TAG=$CONFIG_SERVER_TAG"
        fi
        if [ "$SITE_MANAGEMENT_TAG" != "latest" ] && [ -n "$SITE_MANAGEMENT_TAG" ]; then
          MAKE_ARGS="$MAKE_ARGS SITE_MANAGEMENT_TAG=$SITE_MANAGEMENT_TAG"
        fi
        ISTIO_REPO_BRANCH="${{ inputs.istio-repo-branch }}"
        CORE_MESH_CONFIG_REPO_BRANCH="${{ inputs.core-mesh-config-repo-branch }}"
        if [ -n "$ISTIO_REPO_BRANCH" ]; then
          MAKE_ARGS="$MAKE_ARGS ISTIO_REPO_BRANCH=$ISTIO_REPO_BRANCH"
        fi
        if [ -n "$CORE_MESH_CONFIG_REPO_BRANCH" ]; then
          MAKE_ARGS="$MAKE_ARGS CORE_MESH_CONFIG_REPO_BRANCH=$CORE_MESH_CONFIG_REPO_BRANCH"
        fi
        SERVICE_MESH_TYPE="${{ inputs.service-mesh-type }}"
        if [ -n "$SERVICE_MESH_TYPE" ]; then
          MAKE_ARGS="$MAKE_ARGS SERVICE_MESH_TYPE=$SERVICE_MESH_TYPE"
        fi
        make $MAKE_ARGS -C core-bootstrap-repo/cloud-core-local-dev/ install
