apiVersion: v2
appVersion: "1.0"
description: A Helm chart for the test-service-spring application
name: mesh-test-service-spring
# The effective version will be computed during Helm generation
version: 0.0.1
dependencies:
  - name: coretpl
    version: "0.2.3"
    repository: "https://netcracker.github.io/qubership-core-bootstrap/"

