{{- if eq .Values.SERVICE_MESH_TYPE "ISTIO" }}
apiVersion: v1
kind: Service
metadata:
  name: '{{ .Values.SERVICE }}'
spec:
  ports:
  - name: web
    port: 8080
    targetPort: 8080
  selector:
    name: '{{ .Values.DEPLOYMENT_RESOURCE_NAME }}'
{{- end }}
