{{- if eq .Values.SERVICE_MESH_TYPE "ISTIO" }}
kind: Service
apiVersion: v1
metadata:
    name: '{{ .Values.SERVICE }}'
    labels:
        app.kubernetes.io/part-of: 'mesh-test-app'
spec:
    ports:
    -   name: web
        port: 8080
        targetPort: 8080
    {{ if  eq .Values.K8S_SERVICE_TYPE "HEADLESS" }}
    clusterIP: None
    {{ end }}
{{- else }}
apiVersion: netcracker.com/v1alpha
kind: FacadeService
metadata:
  name: '{{ .Values.SERVICE }}'
spec:
  port: 8080
  env:
    facadeGatewayConcurrency: 1
    facadeGatewayCpuLimit: 100m
    facadeGatewayCpuRequest: 50m
    facadeGatewayMemoryLimit: 64Mi
    facadeGatewayMemoryRequest: 64Mi
  gateway: 'mesh-test-app-gateway'
{{- end}}