apiVersion: core.qubership.org/v1
kind: Gateway
metadata:
  name: egress-gateway
  namespace: "{{ .Values.NAMESPACE }}"
  labels:
    app.kubernetes.io/part-of: 'mesh-test-app'
    app.kubernetes.io/name: '{{ .Values.SERVICE_NAME }}' # needed for finalyzer check
    app.kubernetes.io/processed-by-operator: "core-operator" # name of operator
    app.kubernetes.io/managed-by: "{{ .Values.MANAGED_BY }}"
    deployment.qubership.org/sessionId: '{{ .Values.DEPLOYMENT_SESSION_ID }}' # needed for finalyzer check
spec:
  port: 8080
  env:
    facadeGatewayMemoryLimit: 128Mi
    facadeGatewayConcurrency: 1