name: Cleanup Old Maven JAR Files

on:
  schedule:
    - cron: "10 0 * * 0" # Runs weekly on Sunday at midnight + 10
  workflow_dispatch:
    inputs:
      threshold-days:
        description: "Number of days to keep Maven JAR versions"
        required: false
        default: "14"
      included-patterns:
        description: "Patterns to include for deletion"
        required: false
        default: "*SNAPSHOT"
      excluded-patterns:
        description: "Patterns to exclude from deletion"
        required: false
        default: "latest,release*,*.*"
      debug:
        description: "Enable debug mode"
        required: false
        default: false
        type: "boolean"
      dry-run:
        description: "Enable dry-run mode"
        required: false
        default: false
        type: "boolean"

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Maven Cleanup Action
        uses: netcracker/qubership-workflow-hub/actions/container-package-cleanup@main
        with:
          threshold-days: ${{ github.event.inputs.threshold-days || 14 }}
          included-patterns: ${{ github.event.inputs.included-patterns || '*SNAPSHOT' }}
          excluded-patterns: ${{ github.event.inputs.excluded-patterns || 'latest,release*,*.*' }}
          debug: ${{ github.event.inputs.debug || 'false' }}
          dry-run: ${{ github.event.inputs.dry-run || 'false' }}
          package-type: maven
        env:
          PACKAGE_TOKEN: ${{ secrets.GH_RWD_PACKAGE_TOKEN }}