name: Consul-login-test-service-quarkus build

on:
  push:
    paths:
      - 'consul-login/test-service-quarkus/**'
      - '.github/workflows/consul-login-test-service-quarkus-on-commit.yaml'
  pull_request:
    types: [ opened, synchronize, reopened ]
    paths:
      - 'consul-login/test-service-quarkus/**'
      - '.github/workflows/consul-login-test-service-quarkus-on-commit.yaml'
jobs:
  build:
    uses: netcracker/qubership-core-infra/.github/workflows/generic-maven-build.yaml@ed95ad948025728db1e613a3e1a4e6a11186f541 # v2.6.2
    with:
      maven-command: 'verify'
      pom-file: consul-login/test-service-quarkus/pom.xml
      sonar-project-key: ${{ vars.SONAR_PROJECT_KEY }}
      ref: ${{ github.ref }}
      skip-docker: true
    secrets: inherit
